#ifndef __S2_CONTROLCONFMGMT2_H__
#define __S2_CONTROLCONFMGMT2_H__


#include "S2_CMIS_Hub_Library.h"
#include "S2_CMIS_Hub_Library.h"
#include "S2_CMIS_Hub_Library.h"
#include "S2_CMIS_Hub_Library.h"
#include "S2_CMIS_Hub_Library.h"
#include "S2_CMIS_Hub_Library.h"
#include "S2_CMIS_Hub_Library.h"
#include "S2_CMIS_Hub_Library.h"
#include "S2_CMIS_Hub_Library.h"
#include "S2_CMIS_Hub_Library.h"
#include "S2_CMIS_Hub_Library.h"


/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_ControlConfMgmt2_CONTROL1ACTIVE_DIG_INPUT 0
#define __S2_ControlConfMgmt2_CONTROL2ACTIVE_DIG_INPUT 1

#define __S2_ControlConfMgmt2_ROUTECONTROL1_DIG_INPUT 2
#define __S2_ControlConfMgmt2_ROUTECONTROL1_ARRAY_LENGTH 2
#define __S2_ControlConfMgmt2_ROUTECONTROL2_DIG_INPUT 4
#define __S2_ControlConfMgmt2_ROUTECONTROL2_ARRAY_LENGTH 2
#define __S2_ControlConfMgmt2_DICLOSERIVULETERROR_DIG_INPUT 6
#define __S2_ControlConfMgmt2_DICLOSERIVULETERROR_ARRAY_LENGTH 2

/*
* ANALOG_INPUT
*/

#define __S2_ControlConfMgmt2_SIAUDVIDROUTE_STRING_INPUT 0
#define __S2_ControlConfMgmt2_SIAUDVIDROUTE_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_ControlConfMgmt2, __SIAUDVIDROUTE, __S2_ControlConfMgmt2_SIAUDVIDROUTE_STRING_MAX_LEN );


#define __S2_ControlConfMgmt2_AIRIVULETSTATUSES_ANALOG_INPUT 1
#define __S2_ControlConfMgmt2_AIRIVULETSTATUSES_ARRAY_LENGTH 2
#define __S2_ControlConfMgmt2_SICONTROLCONFMSG_STRING_INPUT 3
#define __S2_ControlConfMgmt2_SICONTROLCONFMSG_ARRAY_NUM_ELEMS 2
#define __S2_ControlConfMgmt2_SICONTROLCONFMSG_ARRAY_NUM_CHARS 30
CREATE_STRING_ARRAY( S2_ControlConfMgmt2, __SICONTROLCONFMSG, __S2_ControlConfMgmt2_SICONTROLCONFMSG_ARRAY_NUM_ELEMS, __S2_ControlConfMgmt2_SICONTROLCONFMSG_ARRAY_NUM_CHARS );
#define __S2_ControlConfMgmt2_SICONTROLSVIDLABEL_STRING_INPUT 5
#define __S2_ControlConfMgmt2_SICONTROLSVIDLABEL_ARRAY_NUM_ELEMS 2
#define __S2_ControlConfMgmt2_SICONTROLSVIDLABEL_ARRAY_NUM_CHARS 30
CREATE_STRING_ARRAY( S2_ControlConfMgmt2, __SICONTROLSVIDLABEL, __S2_ControlConfMgmt2_SICONTROLSVIDLABEL_ARRAY_NUM_ELEMS, __S2_ControlConfMgmt2_SICONTROLSVIDLABEL_ARRAY_NUM_CHARS );
#define __S2_ControlConfMgmt2_SICONTROLDVILABEL_STRING_INPUT 7
#define __S2_ControlConfMgmt2_SICONTROLDVILABEL_ARRAY_NUM_ELEMS 2
#define __S2_ControlConfMgmt2_SICONTROLDVILABEL_ARRAY_NUM_CHARS 30
CREATE_STRING_ARRAY( S2_ControlConfMgmt2, __SICONTROLDVILABEL, __S2_ControlConfMgmt2_SICONTROLDVILABEL_ARRAY_NUM_ELEMS, __S2_ControlConfMgmt2_SICONTROLDVILABEL_ARRAY_NUM_CHARS );

/*
* DIGITAL_OUTPUT
*/

#define __S2_ControlConfMgmt2_DORIVULETCONNERROR_DIG_OUTPUT 0
#define __S2_ControlConfMgmt2_DORIVULETCONNERROR_ARRAY_LENGTH 2
#define __S2_ControlConfMgmt2_DORIVULETDISCERROR_DIG_OUTPUT 2
#define __S2_ControlConfMgmt2_DORIVULETDISCERROR_ARRAY_LENGTH 2
#define __S2_ControlConfMgmt2_DORIVULETGENERROR_DIG_OUTPUT 4
#define __S2_ControlConfMgmt2_DORIVULETGENERROR_ARRAY_LENGTH 2
#define __S2_ControlConfMgmt2_ROUTECONTROL1FB_DIG_OUTPUT 6
#define __S2_ControlConfMgmt2_ROUTECONTROL1FB_ARRAY_LENGTH 2
#define __S2_ControlConfMgmt2_ROUTECONTROL2FB_DIG_OUTPUT 8
#define __S2_ControlConfMgmt2_ROUTECONTROL2FB_ARRAY_LENGTH 2
#define __S2_ControlConfMgmt2_MUTEENDPOINT_DIG_OUTPUT 10
#define __S2_ControlConfMgmt2_MUTEENDPOINT_ARRAY_LENGTH 8
#define __S2_ControlConfMgmt2_CONNECTENDPOINTS_DIG_OUTPUT 18
#define __S2_ControlConfMgmt2_CONNECTENDPOINTS_ARRAY_LENGTH 56

/*
* ANALOG_OUTPUT
*/

#define __S2_ControlConfMgmt2_SOLECTURECONFMSG_STRING_OUTPUT 0
#define __S2_ControlConfMgmt2_SOBREAKOUTCONFMSG_STRING_OUTPUT 1
#define __S2_ControlConfMgmt2_SOLECTURESVIDLABEL_STRING_OUTPUT 2
#define __S2_ControlConfMgmt2_SOBREAKOUTSVIDLABEL_STRING_OUTPUT 3
#define __S2_ControlConfMgmt2_SOLECTUREDVILABEL_STRING_OUTPUT 4
#define __S2_ControlConfMgmt2_SOBREAKOUTDVILABEL_STRING_OUTPUT 5

#define __S2_ControlConfMgmt2_AORIVULETSTATUSLINE1_ANALOG_OUTPUT 10
#define __S2_ControlConfMgmt2_AORIVULETSTATUSLINE1_ARRAY_LENGTH 2
#define __S2_ControlConfMgmt2_AORIVULETSTATUSLINE2_ANALOG_OUTPUT 12
#define __S2_ControlConfMgmt2_AORIVULETSTATUSLINE2_ARRAY_LENGTH 2
#define __S2_ControlConfMgmt2_SOCONTROL1LABELS_STRING_OUTPUT 6
#define __S2_ControlConfMgmt2_SOCONTROL1LABELS_ARRAY_LENGTH 2
#define __S2_ControlConfMgmt2_SOCONTROL2LABELS_STRING_OUTPUT 8
#define __S2_ControlConfMgmt2_SOCONTROL2LABELS_ARRAY_LENGTH 2

/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/
CREATE_INTARRAY1D( S2_ControlConfMgmt2, __GICTRL, 2 );;
CREATE_INTARRAY1D( S2_ControlConfMgmt2, __GICTRLERR, 2 );;


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_ControlConfMgmt2_GSCONTROLCONFMSG_ARRAY_NUM_ELEMS 2
#define __S2_ControlConfMgmt2_GSCONTROLCONFMSG_ARRAY_NUM_CHARS 30
CREATE_STRING_ARRAY( S2_ControlConfMgmt2, __GSCONTROLCONFMSG, __S2_ControlConfMgmt2_GSCONTROLCONFMSG_ARRAY_NUM_ELEMS, __S2_ControlConfMgmt2_GSCONTROLCONFMSG_ARRAY_NUM_CHARS );
#define __S2_ControlConfMgmt2_GSCONTROLSVIDLABEL_ARRAY_NUM_ELEMS 2
#define __S2_ControlConfMgmt2_GSCONTROLSVIDLABEL_ARRAY_NUM_CHARS 30
CREATE_STRING_ARRAY( S2_ControlConfMgmt2, __GSCONTROLSVIDLABEL, __S2_ControlConfMgmt2_GSCONTROLSVIDLABEL_ARRAY_NUM_ELEMS, __S2_ControlConfMgmt2_GSCONTROLSVIDLABEL_ARRAY_NUM_CHARS );
#define __S2_ControlConfMgmt2_GSCONTROLDVILABEL_ARRAY_NUM_ELEMS 2
#define __S2_ControlConfMgmt2_GSCONTROLDVILABEL_ARRAY_NUM_CHARS 30
CREATE_STRING_ARRAY( S2_ControlConfMgmt2, __GSCONTROLDVILABEL, __S2_ControlConfMgmt2_GSCONTROLDVILABEL_ARRAY_NUM_ELEMS, __S2_ControlConfMgmt2_GSCONTROLDVILABEL_ARRAY_NUM_CHARS );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_ControlConfMgmt2 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __ROUTECONTROL1 );
   DECLARE_IO_ARRAY( __ROUTECONTROL2 );
   DECLARE_IO_ARRAY( __DICLOSERIVULETERROR );
   DECLARE_IO_ARRAY( __DORIVULETCONNERROR );
   DECLARE_IO_ARRAY( __DORIVULETDISCERROR );
   DECLARE_IO_ARRAY( __DORIVULETGENERROR );
   DECLARE_IO_ARRAY( __ROUTECONTROL1FB );
   DECLARE_IO_ARRAY( __ROUTECONTROL2FB );
   DECLARE_IO_ARRAY( __MUTEENDPOINT );
   DECLARE_IO_ARRAY( __CONNECTENDPOINTS );
   DECLARE_IO_ARRAY( __AIRIVULETSTATUSES );
   DECLARE_IO_ARRAY( __AORIVULETSTATUSLINE1 );
   DECLARE_IO_ARRAY( __AORIVULETSTATUSLINE2 );
   DECLARE_IO_ARRAY( __SOCONTROL1LABELS );
   DECLARE_IO_ARRAY( __SOCONTROL2LABELS );
   DECLARE_STRING_STRUCT( S2_ControlConfMgmt2, __SIAUDVIDROUTE );
   DECLARE_STRING_ARRAY( S2_ControlConfMgmt2, __SICONTROLCONFMSG );
   DECLARE_STRING_ARRAY( S2_ControlConfMgmt2, __SICONTROLSVIDLABEL );
   DECLARE_STRING_ARRAY( S2_ControlConfMgmt2, __SICONTROLDVILABEL );
};

START_NVRAM_VAR_STRUCT( S2_ControlConfMgmt2 )
{
   DECLARE_STRING_ARRAY( S2_ControlConfMgmt2, __GSCONTROLCONFMSG );
   DECLARE_STRING_ARRAY( S2_ControlConfMgmt2, __GSCONTROLSVIDLABEL );
   DECLARE_STRING_ARRAY( S2_ControlConfMgmt2, __GSCONTROLDVILABEL );
   DECLARE_INTARRAY( S2_ControlConfMgmt2, __GICTRL );
   DECLARE_INTARRAY( S2_ControlConfMgmt2, __GICTRLERR );
};



#endif //__S2_CONTROLCONFMGMT2_H__

