#ifndef __S2_RIVULET_H__
#define __S2_RIVULET_H__


#include "S2_CMIS_Hub_Library.h"
#include "S2_CMIS_Hub_Library.h"
#include "S2_CMIS_Hub_XML.h"
#include "S2_CMIS_Hub_XML.h"

/*
* STRUCTURE S2_Rivulet__VIDEOENDPOINT
*/
#define VIDEOENDPOINT__S2_Rivulet_RIVVEC_IP_STRING_MAX_LEN 20
START_STRUCTURE_DEFINITION( S2_Rivulet, VIDEOENDPOINT )
{
   CREATE_STRING_STRUCT( S2_Rivulet, VIDEOENDPOINT__RIVVEC_IP, VIDEOENDPOINT__S2_Rivulet_RIVVEC_IP_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Rivulet, VIDEOENDPOINT__RIVVEC_IP );
   unsigned short VIDEOENDPOINT__CUSTOMENDPOINTID;
   unsigned short VIDEOENDPOINT__FIXEDENDPOINTID;
   unsigned short VIDEOENDPOINT__SVIDEOINCOUNT;
   unsigned short VIDEOENDPOINT__SVIDEOOUTCOUNT;
   unsigned short VIDEOENDPOINT__SVIDEOINSTART;
   unsigned short VIDEOENDPOINT__SVIDEOOUTSTART;
   unsigned short VIDEOENDPOINT__RIVAUDIOINCNT;
   unsigned short VIDEOENDPOINT__RIVAUDIOOUTCNT;
   unsigned short VIDEOENDPOINT__RIVDVIINCNT;
   unsigned short VIDEOENDPOINT__RIVDVIOUTCNT;
   unsigned short VIDEOENDPOINT__RIVSVIDEOINCNT;
   unsigned short VIDEOENDPOINT__RIVSVIDEOOUTCNT;
   unsigned short VIDEOENDPOINT__RIVENDPOINTTYPE;
   unsigned short VIDEOENDPOINT__PRIVACY;
   CREATE_INTARRAY1D( S2_Rivulet, VIDEOENDPOINT__STATUS, 4 );;
   DECLARE_INTARRAY( S2_Rivulet, VIDEOENDPOINT__STATUS );
};

/*
* STRUCTURE S2_Rivulet__CONNECTION
*/
#define CONNECTION__S2_Rivulet_ERRORSTRING_STRING_MAX_LEN 200
#define CONNECTION__S2_Rivulet_VEC_IP_STRING_MAX_LEN 20
#define CONNECTION__S2_Rivulet_CORRELATIONID1_STRING_MAX_LEN 20
#define CONNECTION__S2_Rivulet_CORRELATIONID2_STRING_MAX_LEN 20
#define CONNECTION__S2_Rivulet_CORRELATIONID3_STRING_MAX_LEN 20
#define CONNECTION__S2_Rivulet_CORRELATIONID4_STRING_MAX_LEN 20
#define CONNECTION__S2_Rivulet_SERVICEID1_STRING_MAX_LEN 20
#define CONNECTION__S2_Rivulet_SERVICEID2_STRING_MAX_LEN 20
#define CONNECTION__S2_Rivulet_SERVICEID3_STRING_MAX_LEN 20
#define CONNECTION__S2_Rivulet_SERVICEID4_STRING_MAX_LEN 20
START_STRUCTURE_DEFINITION( S2_Rivulet, CONNECTION )
{
   CREATE_STRING_STRUCT( S2_Rivulet, CONNECTION__ERRORSTRING, CONNECTION__S2_Rivulet_ERRORSTRING_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Rivulet, CONNECTION__ERRORSTRING );
   CREATE_STRING_STRUCT( S2_Rivulet, CONNECTION__VEC_IP, CONNECTION__S2_Rivulet_VEC_IP_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Rivulet, CONNECTION__VEC_IP );
   CREATE_STRING_STRUCT( S2_Rivulet, CONNECTION__CORRELATIONID1, CONNECTION__S2_Rivulet_CORRELATIONID1_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Rivulet, CONNECTION__CORRELATIONID1 );
   CREATE_STRING_STRUCT( S2_Rivulet, CONNECTION__CORRELATIONID2, CONNECTION__S2_Rivulet_CORRELATIONID2_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Rivulet, CONNECTION__CORRELATIONID2 );
   CREATE_STRING_STRUCT( S2_Rivulet, CONNECTION__CORRELATIONID3, CONNECTION__S2_Rivulet_CORRELATIONID3_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Rivulet, CONNECTION__CORRELATIONID3 );
   CREATE_STRING_STRUCT( S2_Rivulet, CONNECTION__CORRELATIONID4, CONNECTION__S2_Rivulet_CORRELATIONID4_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Rivulet, CONNECTION__CORRELATIONID4 );
   CREATE_STRING_STRUCT( S2_Rivulet, CONNECTION__SERVICEID1, CONNECTION__S2_Rivulet_SERVICEID1_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Rivulet, CONNECTION__SERVICEID1 );
   CREATE_STRING_STRUCT( S2_Rivulet, CONNECTION__SERVICEID2, CONNECTION__S2_Rivulet_SERVICEID2_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Rivulet, CONNECTION__SERVICEID2 );
   CREATE_STRING_STRUCT( S2_Rivulet, CONNECTION__SERVICEID3, CONNECTION__S2_Rivulet_SERVICEID3_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Rivulet, CONNECTION__SERVICEID3 );
   CREATE_STRING_STRUCT( S2_Rivulet, CONNECTION__SERVICEID4, CONNECTION__S2_Rivulet_SERVICEID4_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Rivulet, CONNECTION__SERVICEID4 );
   unsigned short CONNECTION__ROOM1;
   unsigned short CONNECTION__ROOM2;
   unsigned short CONNECTION__CURRQST;
   unsigned short CONNECTION__CURSTATUS;
   unsigned short CONNECTION__AUDIOCNT;
   unsigned short CONNECTION__DVICNT;
   unsigned short CONNECTION__SVIDEOCNT;
   unsigned short CONNECTION__TYPE;
};

/*
* STRUCTURE S2_Rivulet__RESPONSEDATA
*/
#define RESPONSEDATA__S2_Rivulet_COORELATIONID_STRING_MAX_LEN 20
#define RESPONSEDATA__S2_Rivulet_SERVICEID_STRING_MAX_LEN 20
#define RESPONSEDATA__S2_Rivulet_API_CMD_RESP_STRING_MAX_LEN 50
#define RESPONSEDATA__S2_Rivulet_API_CMD_ERROR_STRING_MAX_LEN 100
#define RESPONSEDATA__S2_Rivulet_ENDPOINT_ALIAS_STRING_MAX_LEN 20
#define RESPONSEDATA__S2_Rivulet_ENDPOINT_STATUS_STRING_MAX_LEN 20
START_STRUCTURE_DEFINITION( S2_Rivulet, RESPONSEDATA )
{
   CREATE_STRING_STRUCT( S2_Rivulet, RESPONSEDATA__COORELATIONID, RESPONSEDATA__S2_Rivulet_COORELATIONID_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Rivulet, RESPONSEDATA__COORELATIONID );
   CREATE_STRING_STRUCT( S2_Rivulet, RESPONSEDATA__SERVICEID, RESPONSEDATA__S2_Rivulet_SERVICEID_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Rivulet, RESPONSEDATA__SERVICEID );
   CREATE_STRING_STRUCT( S2_Rivulet, RESPONSEDATA__API_CMD_RESP, RESPONSEDATA__S2_Rivulet_API_CMD_RESP_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Rivulet, RESPONSEDATA__API_CMD_RESP );
   CREATE_STRING_STRUCT( S2_Rivulet, RESPONSEDATA__API_CMD_ERROR, RESPONSEDATA__S2_Rivulet_API_CMD_ERROR_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Rivulet, RESPONSEDATA__API_CMD_ERROR );
   CREATE_STRING_STRUCT( S2_Rivulet, RESPONSEDATA__ENDPOINT_ALIAS, RESPONSEDATA__S2_Rivulet_ENDPOINT_ALIAS_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Rivulet, RESPONSEDATA__ENDPOINT_ALIAS );
   CREATE_STRING_STRUCT( S2_Rivulet, RESPONSEDATA__ENDPOINT_STATUS, RESPONSEDATA__S2_Rivulet_ENDPOINT_STATUS_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Rivulet, RESPONSEDATA__ENDPOINT_STATUS );
   unsigned short RESPONSEDATA__INUSE;
};

/*
* STRUCTURE S2_Rivulet__FIXED_ENDPOINT
*/
START_STRUCTURE_DEFINITION( S2_Rivulet, FIXED_ENDPOINT )
{
   CREATE_INTARRAY1D( S2_Rivulet, FIXED_ENDPOINT__SOURCE, 32 );;
   DECLARE_INTARRAY( S2_Rivulet, FIXED_ENDPOINT__SOURCE );
   CREATE_INTARRAY1D( S2_Rivulet, FIXED_ENDPOINT__TARGET, 32 );;
   DECLARE_INTARRAY( S2_Rivulet, FIXED_ENDPOINT__TARGET );
};


/*
* Constructor and Destructor
*/
int S2_Rivulet_VIDEOENDPOINT_Constructor ( START_STRUCTURE_DEFINITION( S2_Rivulet, VIDEOENDPOINT ) * me, int nVerbose );
int S2_Rivulet_VIDEOENDPOINT_Destructor ( START_STRUCTURE_DEFINITION( S2_Rivulet, VIDEOENDPOINT ) * me, int nVerbose );
int S2_Rivulet_CONNECTION_Constructor ( START_STRUCTURE_DEFINITION( S2_Rivulet, CONNECTION ) * me, int nVerbose );
int S2_Rivulet_CONNECTION_Destructor ( START_STRUCTURE_DEFINITION( S2_Rivulet, CONNECTION ) * me, int nVerbose );
int S2_Rivulet_RESPONSEDATA_Constructor ( START_STRUCTURE_DEFINITION( S2_Rivulet, RESPONSEDATA ) * me, int nVerbose );
int S2_Rivulet_RESPONSEDATA_Destructor ( START_STRUCTURE_DEFINITION( S2_Rivulet, RESPONSEDATA ) * me, int nVerbose );
int S2_Rivulet_FIXED_ENDPOINT_Constructor ( START_STRUCTURE_DEFINITION( S2_Rivulet, FIXED_ENDPOINT ) * me, int nVerbose );
int S2_Rivulet_FIXED_ENDPOINT_Destructor ( START_STRUCTURE_DEFINITION( S2_Rivulet, FIXED_ENDPOINT ) * me, int nVerbose );

/*
* DIGITAL_INPUT
*/
#define __S2_Rivulet_SIGSTARTUPCOMPLETE_DIG_INPUT 0
#define __S2_Rivulet_SIGRIVULETCONNECTED_DIG_INPUT 1
#define __S2_Rivulet_DIDEBUG_DIG_INPUT 2


/*
* ANALOG_INPUT
*/
#define __S2_Rivulet_AIRIVLINKSTATUS_ANALOG_INPUT 0

#define __S2_Rivulet_RXRIVULET_STRING_INPUT 1
#define __S2_Rivulet_RXRIVULET_STRING_MAX_LEN 255
CREATE_STRING_STRUCT( S2_Rivulet, __RXRIVULET, __S2_Rivulet_RXRIVULET_STRING_MAX_LEN );
#define __S2_Rivulet_SIRIVULETCONFIG_STRING_INPUT 2
#define __S2_Rivulet_SIRIVULETCONFIG_STRING_MAX_LEN 255
CREATE_STRING_STRUCT( S2_Rivulet, __SIRIVULETCONFIG, __S2_Rivulet_SIRIVULETCONFIG_STRING_MAX_LEN );
#define __S2_Rivulet_SIVIDROUTE_STRING_INPUT 3
#define __S2_Rivulet_SIVIDROUTE_STRING_MAX_LEN 255
CREATE_STRING_STRUCT( S2_Rivulet, __SIVIDROUTE, __S2_Rivulet_SIVIDROUTE_STRING_MAX_LEN );



/*
* DIGITAL_OUTPUT
*/
#define __S2_Rivulet_DORIVLINKENABLE_DIG_OUTPUT 0


/*
* ANALOG_OUTPUT
*/

#define __S2_Rivulet_TXRIVULET_STRING_OUTPUT 0

#define __S2_Rivulet_AOENDPOINTSTATUS_ANALOG_OUTPUT 1
#define __S2_Rivulet_AOENDPOINTSTATUS_ARRAY_LENGTH 24

/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/
CREATE_INTARRAY1D( S2_Rivulet, __GIXMLDATA, 20 );;


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_Rivulet_GSRESPONSEMSG_STRING_MAX_LEN 1024
CREATE_STRING_STRUCT( S2_Rivulet, __GSRESPONSEMSG, __S2_Rivulet_GSRESPONSEMSG_STRING_MAX_LEN );
#define __S2_Rivulet_GSXMLPARAMS_STRING_MAX_LEN 4096
CREATE_STRING_STRUCT( S2_Rivulet, __GSXMLPARAMS, __S2_Rivulet_GSXMLPARAMS_STRING_MAX_LEN );
#define __S2_Rivulet_GSRIVULETSESSIONID_STRING_MAX_LEN 50
CREATE_STRING_STRUCT( S2_Rivulet, __GSRIVULETSESSIONID, __S2_Rivulet_GSRIVULETSESSIONID_STRING_MAX_LEN );
#define __S2_Rivulet_GSXMLSTRINGS_ARRAY_NUM_ELEMS 20
#define __S2_Rivulet_GSXMLSTRINGS_ARRAY_NUM_CHARS 255
CREATE_STRING_ARRAY( S2_Rivulet, __GSXMLSTRINGS, __S2_Rivulet_GSXMLSTRINGS_ARRAY_NUM_ELEMS, __S2_Rivulet_GSXMLSTRINGS_ARRAY_NUM_CHARS );
#define __S2_Rivulet_GSXMLFILETAGS_ARRAY_NUM_ELEMS 100
#define __S2_Rivulet_GSXMLFILETAGS_ARRAY_NUM_CHARS 64
CREATE_STRING_ARRAY( S2_Rivulet, __GSXMLFILETAGS, __S2_Rivulet_GSXMLFILETAGS_ARRAY_NUM_ELEMS, __S2_Rivulet_GSXMLFILETAGS_ARRAY_NUM_CHARS );

/*
* STRUCTURE
*/
#define __S2_Rivulet_CONNECTIONLIST_STRUCT_MAX_LEN 24
CREATE_STRUCTURE_ARRAY( S2_Rivulet, __CONNECTIONLIST, CONNECTION, __S2_Rivulet_CONNECTIONLIST_STRUCT_MAX_LEN );
#define __S2_Rivulet_ENDPOINTS_STRUCT_MAX_LEN 24
CREATE_STRUCTURE_ARRAY( S2_Rivulet, __ENDPOINTS, VIDEOENDPOINT, __S2_Rivulet_ENDPOINTS_STRUCT_MAX_LEN );
#define __S2_Rivulet_RESPONSELIST_STRUCT_MAX_LEN 20
CREATE_STRUCTURE_ARRAY( S2_Rivulet, __RESPONSELIST, RESPONSEDATA, __S2_Rivulet_RESPONSELIST_STRUCT_MAX_LEN );
#define __S2_Rivulet_FIXEDROUTINGTABLE_STRUCT_MAX_LEN 8
CREATE_STRUCTURE_ARRAY( S2_Rivulet, __FIXEDROUTINGTABLE, FIXED_ENDPOINT, __S2_Rivulet_FIXEDROUTINGTABLE_STRUCT_MAX_LEN );

START_GLOBAL_VAR_STRUCT( S2_Rivulet )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __AOENDPOINTSTATUS );
   DECLARE_STRING_STRUCT( S2_Rivulet, __RXRIVULET );
   DECLARE_STRING_STRUCT( S2_Rivulet, __SIRIVULETCONFIG );
   DECLARE_STRING_STRUCT( S2_Rivulet, __SIVIDROUTE );
};

START_NVRAM_VAR_STRUCT( S2_Rivulet )
{
   DECLARE_STRING_STRUCT( S2_Rivulet, __GSRESPONSEMSG );
   DECLARE_STRING_STRUCT( S2_Rivulet, __GSXMLPARAMS );
   DECLARE_STRING_STRUCT( S2_Rivulet, __GSRIVULETSESSIONID );
   DECLARE_STRING_ARRAY( S2_Rivulet, __GSXMLSTRINGS );
   DECLARE_STRING_ARRAY( S2_Rivulet, __GSXMLFILETAGS );
   unsigned short __GICONNECTEDTORIVULET;
   unsigned short __GINHIBITBOUNCE;
   unsigned short __GIRIVULETREADY;
   unsigned short __GIRIVULETCONFIGURED;
   unsigned short __GIRIVULETCOORID;
   DECLARE_INTARRAY( S2_Rivulet, __GIXMLDATA );
   DECLARE_STRUCT_ARRAY( S2_Rivulet, __CONNECTIONLIST );
   DECLARE_STRUCT_ARRAY( S2_Rivulet, __ENDPOINTS );
   DECLARE_STRUCT_ARRAY( S2_Rivulet, __RESPONSELIST );
   DECLARE_STRUCT_ARRAY( S2_Rivulet, __FIXEDROUTINGTABLE );
};



#endif //__S2_RIVULET_H__

