#ifndef __S2_CONTROLCONFMGMT_H__
#define __S2_CONTROLCONFMGMT_H__


#include "S2_CMIS_Hub_Library.h"
#include "S2_CMIS_Hub_Library.h"


/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_ControlConfMgmt_CONTROL1ACTIVE_DIG_INPUT 0
#define __S2_ControlConfMgmt_CONTROL2ACTIVE_DIG_INPUT 1

#define __S2_ControlConfMgmt_ROUTECONTROL1_DIG_INPUT 2
#define __S2_ControlConfMgmt_ROUTECONTROL1_ARRAY_LENGTH 2
#define __S2_ControlConfMgmt_ROUTECONTROL2_DIG_INPUT 4
#define __S2_ControlConfMgmt_ROUTECONTROL2_ARRAY_LENGTH 2

/*
* ANALOG_INPUT
*/

#define __S2_ControlConfMgmt_SIAUDVIDROUTE_STRING_INPUT 0
#define __S2_ControlConfMgmt_SIAUDVIDROUTE_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_ControlConfMgmt, __SIAUDVIDROUTE, __S2_ControlConfMgmt_SIAUDVIDROUTE_STRING_MAX_LEN );


#define __S2_ControlConfMgmt_SICONTROLCONFMSG_STRING_INPUT 1
#define __S2_ControlConfMgmt_SICONTROLCONFMSG_ARRAY_NUM_ELEMS 2
#define __S2_ControlConfMgmt_SICONTROLCONFMSG_ARRAY_NUM_CHARS 30
CREATE_STRING_ARRAY( S2_ControlConfMgmt, __SICONTROLCONFMSG, __S2_ControlConfMgmt_SICONTROLCONFMSG_ARRAY_NUM_ELEMS, __S2_ControlConfMgmt_SICONTROLCONFMSG_ARRAY_NUM_CHARS );
#define __S2_ControlConfMgmt_SICONTROLSVIDLABEL_STRING_INPUT 3
#define __S2_ControlConfMgmt_SICONTROLSVIDLABEL_ARRAY_NUM_ELEMS 2
#define __S2_ControlConfMgmt_SICONTROLSVIDLABEL_ARRAY_NUM_CHARS 30
CREATE_STRING_ARRAY( S2_ControlConfMgmt, __SICONTROLSVIDLABEL, __S2_ControlConfMgmt_SICONTROLSVIDLABEL_ARRAY_NUM_ELEMS, __S2_ControlConfMgmt_SICONTROLSVIDLABEL_ARRAY_NUM_CHARS );
#define __S2_ControlConfMgmt_SICONTROLDVILABEL_STRING_INPUT 5
#define __S2_ControlConfMgmt_SICONTROLDVILABEL_ARRAY_NUM_ELEMS 2
#define __S2_ControlConfMgmt_SICONTROLDVILABEL_ARRAY_NUM_CHARS 30
CREATE_STRING_ARRAY( S2_ControlConfMgmt, __SICONTROLDVILABEL, __S2_ControlConfMgmt_SICONTROLDVILABEL_ARRAY_NUM_ELEMS, __S2_ControlConfMgmt_SICONTROLDVILABEL_ARRAY_NUM_CHARS );

/*
* DIGITAL_OUTPUT
*/

#define __S2_ControlConfMgmt_ROUTECONTROL1FB_DIG_OUTPUT 0
#define __S2_ControlConfMgmt_ROUTECONTROL1FB_ARRAY_LENGTH 2
#define __S2_ControlConfMgmt_ROUTECONTROL2FB_DIG_OUTPUT 2
#define __S2_ControlConfMgmt_ROUTECONTROL2FB_ARRAY_LENGTH 2
#define __S2_ControlConfMgmt_MUTEENDPOINT_DIG_OUTPUT 4
#define __S2_ControlConfMgmt_MUTEENDPOINT_ARRAY_LENGTH 8
#define __S2_ControlConfMgmt_CONNECTENDPOINTS_DIG_OUTPUT 12
#define __S2_ControlConfMgmt_CONNECTENDPOINTS_ARRAY_LENGTH 56

/*
* ANALOG_OUTPUT
*/

#define __S2_ControlConfMgmt_SOLECTURECONFMSG_STRING_OUTPUT 0
#define __S2_ControlConfMgmt_SOBREAKOUTCONFMSG_STRING_OUTPUT 1
#define __S2_ControlConfMgmt_SOLECTURESVIDLABEL_STRING_OUTPUT 2
#define __S2_ControlConfMgmt_SOBREAKOUTSVIDLABEL_STRING_OUTPUT 3
#define __S2_ControlConfMgmt_SOLECTUREDVILABEL_STRING_OUTPUT 4
#define __S2_ControlConfMgmt_SOBREAKOUTDVILABEL_STRING_OUTPUT 5


/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_ControlConfMgmt_SCONTROLCONFMSG_ARRAY_NUM_ELEMS 2
#define __S2_ControlConfMgmt_SCONTROLCONFMSG_ARRAY_NUM_CHARS 30
CREATE_STRING_ARRAY( S2_ControlConfMgmt, __SCONTROLCONFMSG, __S2_ControlConfMgmt_SCONTROLCONFMSG_ARRAY_NUM_ELEMS, __S2_ControlConfMgmt_SCONTROLCONFMSG_ARRAY_NUM_CHARS );
#define __S2_ControlConfMgmt_SCONTROLSVIDLABEL_ARRAY_NUM_ELEMS 2
#define __S2_ControlConfMgmt_SCONTROLSVIDLABEL_ARRAY_NUM_CHARS 30
CREATE_STRING_ARRAY( S2_ControlConfMgmt, __SCONTROLSVIDLABEL, __S2_ControlConfMgmt_SCONTROLSVIDLABEL_ARRAY_NUM_ELEMS, __S2_ControlConfMgmt_SCONTROLSVIDLABEL_ARRAY_NUM_CHARS );
#define __S2_ControlConfMgmt_SCONTROLDVILABEL_ARRAY_NUM_ELEMS 2
#define __S2_ControlConfMgmt_SCONTROLDVILABEL_ARRAY_NUM_CHARS 30
CREATE_STRING_ARRAY( S2_ControlConfMgmt, __SCONTROLDVILABEL, __S2_ControlConfMgmt_SCONTROLDVILABEL_ARRAY_NUM_ELEMS, __S2_ControlConfMgmt_SCONTROLDVILABEL_ARRAY_NUM_CHARS );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_ControlConfMgmt )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __ROUTECONTROL1 );
   DECLARE_IO_ARRAY( __ROUTECONTROL2 );
   DECLARE_IO_ARRAY( __ROUTECONTROL1FB );
   DECLARE_IO_ARRAY( __ROUTECONTROL2FB );
   DECLARE_IO_ARRAY( __MUTEENDPOINT );
   DECLARE_IO_ARRAY( __CONNECTENDPOINTS );
   DECLARE_STRING_STRUCT( S2_ControlConfMgmt, __SIAUDVIDROUTE );
   DECLARE_STRING_ARRAY( S2_ControlConfMgmt, __SICONTROLCONFMSG );
   DECLARE_STRING_ARRAY( S2_ControlConfMgmt, __SICONTROLSVIDLABEL );
   DECLARE_STRING_ARRAY( S2_ControlConfMgmt, __SICONTROLDVILABEL );
};

START_NVRAM_VAR_STRUCT( S2_ControlConfMgmt )
{
   DECLARE_STRING_ARRAY( S2_ControlConfMgmt, __SCONTROLCONFMSG );
   DECLARE_STRING_ARRAY( S2_ControlConfMgmt, __SCONTROLSVIDLABEL );
   DECLARE_STRING_ARRAY( S2_ControlConfMgmt, __SCONTROLDVILABEL );
   unsigned short __ICTRL1;
   unsigned short __ICTRL2;
};



#endif //__S2_CONTROLCONFMGMT_H__

